"""Storage interface. `MockDatabase` implements it in memory; a SQLAlchemy version can replace it later."""

from datetime import datetime
from typing import Protocol

from app.models import Expense, Group, Settlement, User


class Database(Protocol):
    # Users
    def add_user(self, user: User) -> None: ...
    def get_user(self, user_id: str) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_user_by_username(self, username: str) -> User | None:
        """Case-insensitive match."""
        ...

    # Groups
    def add_group(self, group: Group) -> None: ...
    def get_group(self, group_id: str) -> Group | None: ...
    def list_groups_for_user(self, user_id: str) -> list[Group]:
        """Newest first."""
        ...

    def add_group_member(self, group_id: str, user_id: str) -> None: ...

    # Expenses
    def add_expense(self, expense: Expense) -> None: ...
    def list_expenses(self, group_id: str) -> list[Expense]:
        """Newest first."""
        ...

    # Settlements
    def add_settlement(self, settlement: Settlement) -> None: ...
    def list_settlements(self, group_id: str) -> list[Settlement]:
        """Newest first."""
        ...

    # Revoked JWTs (logout)
    def revoke_token(self, jti: str, expires_at: datetime) -> None: ...
    def is_token_revoked(self, jti: str) -> bool: ...
